exports.LOCAL_DEVELOPMENT = "LC_DV"
exports.LOCAL_PRODUCTION = "LC_PD"
exports.REMOTE_DEVELOPMENT = "RM_DV"
exports.REMOTE_TESTING = "RM_TS"
exports.REMOTE_STAGING = "RM_SG"
exports.REMOTE_PRODUCTION = "RM_PD"

exports.KIND_OF_LOCAL = "LC"
exports.KIND_OF_REMOTE = "RM"

exports.VARIANT_OF_DEVELOPMENT = "DV"
exports.VARIANT_OF_TESTING = "TS"
exports.VARIANT_OF_STAGING = "SG"
exports.VARIANT_OF_PRODUCTION = "PD"
